<a href="https://colab.research.google.com/github/Vivek6375/Machine-Learning/blob/main/Copy_of_Linear_Regression_from_Scratch_on_2_GB_Used_Car_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import files

In [ ]:
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"vivekchauhan978","key":"d60761110dbafbecd7043d38af2fae54"}'}

In [ ]:
!mkdir ~/.kaggle

In [ ]:
!mv /content/kaggle.json ~/.kaggle

In [ ]:
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.5.16)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from kaggle) (2023.11.17)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.1)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.1)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.6)

In [ ]:
!kaggle datasets download -d austinreese/craigslist-carstrucks-data

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/kaggle/cli.py", line 70, in main
    out = args.func(**command_args)
  File "/usr/local/lib/python3.10/dist-packages/kaggle/api/kaggle_api_extended.py", line 1493, in dataset_download_cli
    self.dataset_download_files(dataset,
  File "/usr/local/lib/python3.10/dist-packages/kaggle/api/kaggle_api_extended.py", line 1447, in dataset_download_files
    self.download_file(response, outfile, quiet, not force)
  File "/usr/local/lib/python3.10/dist-packages/kaggle/api/kaggle_api_extended.py", line 1834, in download_file
    size = int(response.headers['Content-Length'])
  File "/usr/local/lib/python3.10/dist-packages/urllib3/_collections.py", line 258, in __getitem__
    val = self._container[key.lower()]
KeyError: 'content-length'

In [ ]:
!unzip /content/craigslist-carstrucks-data.zip

unzip:  cannot find or open /content/craigslist-carstrucks-data.zip, /content/craigslist-carstrucks-data.zip.zip or /content/craigslist-carstrucks-data.zip.ZIP.

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/vehicles.csv")

In [ ]:
data.head()

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN

In [ ]:
data.columns

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status',
       'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color',
       'image_url', 'description', 'county', 'state', 'lat', 'long',
       'posting_date'],
      dtype='object')

In [ ]:
data.shape

(426880, 26)

In [ ]:
data.isna().sum()

id                   0
url                  0
region               0
region_url           0
price                0
year              1205
manufacturer     17646
model             5277
condition       174104
cylinders       177678
fuel              3013
odometer          4400
title_status      8242
transmission      2556
VIN             161042
drive           130567
size            306361
type             92858
paint_color     130203
image_url           68
description         70
county          426880
state                0
lat               6549
long              6549
posting_date        68
dtype: int64

In [ ]:
data.drop(labels=data.columns[0:4],axis=1,inplace=True)

In [ ]:
data.shape

(426880, 22)

In [ ]:
data.head()

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,11900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,4900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN

In [ ]:
data.drop(labels="title_status",axis=1,inplace=True)

In [ ]:
data.head()

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,transmission,VIN,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,11900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,4900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN

In [ ]:
data.columns

Index(['price', 'year', 'manufacturer', 'model', 'condition', 'cylinders',
       'fuel', 'odometer', 'transmission', 'VIN', 'drive', 'size', 'type',
       'paint_color', 'image_url', 'description', 'county', 'state', 'lat',
       'long', 'posting_date'],
      dtype='object')

In [ ]:
data.drop(labels=data.columns[14:],axis=1,inplace=True)

In [ ]:
data.head()

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,transmission,VIN,drive,size,type,paint_color
0,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data[data["VIN"].notnull()]

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,transmission,VIN,drive,size,type,paint_color
27,33590,2014.0,gmc,sierra 1500 crew cab slt,good,8 cylinders,gas,57923.0,other,3GTP1VEC4EG551563,NaN,NaN,pickup,white
28,22590,2010.0,chevrolet,silverado 1500,good,8 cylinders,gas,71229.0,other,1GCSCSE06AZ123805,NaN,NaN,pickup,blue
29,39590,2020.0,chevrolet,silverado 1500 crew,good,8 cylinders,gas,19160.0,other,3GCPWCED5LG130317,NaN,NaN,pickup,red
30,30990,2017.0,toyota,tundra double cab sr,good,8 cylinders,gas,41124.0,other,5TFRM5F17HX120972,NaN,NaN,pickup,red
32,27990,2012.0,gmc,sierra 2500 hd extended cab,good,8 cylinders,gas,68696.0,other,1GT220CG8CZ231238,4wd,NaN,pickup,black
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426875,23590,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,gas,32226.0,other,1N4AA6AV6KC367801,fwd,NaN,sedan,NaN
426876,30590,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,gas,12029.0,other,7JR102FKXLG042696,fwd,NaN,sedan,red
426877,34990,2020.0,cadillac,xt4 sport suv 4d,good,NaN,diesel,4174.0,other,1GYFZFR46LF088296,NaN,NaN,hatchback,white
426878,28990,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,gas,30112.0,other,58ABK1GG4JU103853,fwd,NaN,sedan,silver
426879,30590,2019.0,bmw,4 series 430i gran coupe,good,NaN,gas,22716.0,other,WBA4J1C58KBM14708,rwd,NaN,coupe,NaN

In [ ]:
data.drop(labels="VIN",axis=1,inplace=True)

In [ ]:
data.head()

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,transmission,drive,size,type,paint_color
0,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.shape

(426880, 13)

In [ ]:
data.columns

Index(['price', 'year', 'manufacturer', 'model', 'condition', 'cylinders',
       'fuel', 'odometer', 'transmission', 'drive', 'size', 'type',
       'paint_color'],
      dtype='object')

In [ ]:
data.dropna(axis=0,thresh=12,inplace=True)

In [ ]:
data.shape

(144017, 13)

In [ ]:
data.head()

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,transmission,drive,size,type,paint_color
31,15000,2013.0,ford,f-150 xlt,excellent,6 cylinders,gas,128000.0,automatic,rwd,full-size,truck,black
32,27990,2012.0,gmc,sierra 2500 hd extended cab,good,8 cylinders,gas,68696.0,other,4wd,NaN,pickup,black
33,34590,2016.0,chevrolet,silverado 1500 double,good,6 cylinders,gas,29499.0,other,4wd,NaN,pickup,silver
34,35000,2019.0,toyota,tacoma,excellent,6 cylinders,gas,43000.0,automatic,4wd,NaN,truck,grey
35,29990,2016.0,chevrolet,colorado extended cab,good,6 cylinders,gas,17302.0,other,4wd,NaN,pickup,red

In [ ]:
data.isna().sum()

price               0
year                0
manufacturer     4059
model             975
condition       13570
cylinders        1766
fuel                0
odometer          408
transmission       11
drive            2491
size            36793
type             1893
paint_color      2856
dtype: int64

In [ ]:
data["manufacturer"].value_counts()

ford               24663
chevrolet          21040
toyota             12227
honda               8115
nissan              7261
jeep                6783
gmc                 5635
ram                 5199
dodge               4886
bmw                 4699
mercedes-benz       4443
hyundai             3202
subaru              3136
lexus               2874
volkswagen          2750
kia                 2429
chrysler            2293
cadillac            2065
buick               1810
infiniti            1673
audi                1633
mazda               1597
acura               1494
lincoln             1410
pontiac             1014
mitsubishi           982
volvo                947
mini                 715
rover                593
mercury              583
saturn               459
jaguar               450
porsche              432
fiat                 203
alfa-romeo            88
tesla                 61
harley-davidson       49
ferrari               28
datsun                24
land rover             8
aston-martin           5
Name: manufacturer, dtype: int64

In [ ]:
data["manufacturer"].fillna(value="ford",inplace=True)

In [ ]:
data.isna().sum()

price               0
year                0
manufacturer        0
model             975
condition       13570
cylinders        1766
fuel                0
odometer          408
transmission       11
drive            2491
size            36793
type             1893
paint_color      2856
dtype: int64

In [ ]:
year = np.array(data["year"])
manufacturer = np.array(data["manufacturer"])
model = np.array(data["model"])

In [ ]:
crosstab_df = pd.crosstab([manufacturer,year],model,rownames=["manufacturer","year"],colnames=["model"])

In [ ]:
crosstab_df

model                "t"  %  & altima  '99 H1 Hummer  (210)  (300)  \
manufacturer year
acura        1900.0    0  0         0              0      0      0
             1991.0    0  0         0              0      0      0
             1992.0    0  0         0              0      0      0
             1993.0    0  0         0              0      0      0
             1994.0    0  0         0              0      0      0
...                  ... ..       ...            ...    ...    ...
volvo        1966.0    0  0         0              0      0      0
             1967.0    0  0         0              0      0      0
             1970.0    0  0         0              0      0      0
             1971.0    0  0         0              0      0      0
             1972.0    0  0         0              0      0      0

model                (cng) 2500 express van  (s)port (s)edan  * vmi * ♿  -  \
manufacturer year
acura        1900.0                       0                0          0  0
             1991.0                       0                0          0  0
             1992.0                       0                0          0  0
             1993.0                       0                0          0  0
             1994.0                       0                0          0  0
...                                     ...              ...        ... ..
volvo        1966.0                       0                0          0  0
             1967.0                       0                0          0  0
             1970.0                       0                0          0  0
             1971.0                       0                0          0  0
             1972.0                       0                0          0  0

model                ...  z4 sdrive35i  z4 sdrive35is  z71  zdx  zephyr  \
manufacturer year    ...
acura        1900.0  ...             0              0    0    0       0
             1991.0  ...             0              0    0    0       0
             1992.0  ...             0              0    0    0       0
             1993.0  ...             0              0    0    0       0
             1994.0  ...             0              0    0    0       0
...                  ...           ...            ...  ...  ...     ...
volvo        1966.0  ...             0              0    0    0       0
             1967.0  ...             0              0    0    0       0
             1970.0  ...             0              0    0    0       0
             1971.0  ...             0              0    0    0       0
             1972.0  ...             0              0    0    0       0

model                zl1 camaro  zr2 sonoma  zx2  ♿  ♿ vmi
manufacturer year
acura        1900.0           0           0    0  0      0
             1991.0           0           0    0  0      0
             1992.0           0           0    0  0      0
             1993.0           0           0    0  0      0
             1994.0           0           0    0  0      0
...                         ...         ...  ... ..    ...
volvo        1966.0           0           0    0  0      0
             1967.0           0           0    0  0      0
             1970.0           0           0    0  0      0
             1971.0           0           0    0  0      0
             1972.0           0           0    0  0      0

[1708 rows x 14487 columns]

In [ ]:
len(data["manufacturer"].unique())

41

In [ ]:
data["year"].unique()

array([2013., 2012., 2016., 2019., 2011., 2017., 2018., 2004., 2001.,
       2014., 2003., 2008., 2007., 2005., 2020., 1966., 2006., 2010.,
       2009., 2002., 2015., 1998., 1995., 1978., 1974., 1996., 1987.,
       2000., 1955., 1972., 2021., 1994., 1999., 1988., 1979., 1984.,
       1992., 1937., 1976., 1991., 1953., 1963., 1968., 1997., 1993.,
       1990., 1982., 1948., 1986., 1983., 1985., 1951., 1936., 1980.,
       1989., 1967., 1981., 1973., 1947., 1962., 1975., 1958., 1964.,
       1977., 1971., 1970., 1946., 1969., 1957., 1959., 1930., 1965.,
       1928., 1933., 1960., 1952., 1929., 1932., 1956., 1950., 1924.,
       1927., 1939., 1923., 1934., 1940., 1961., 1935., 1942., 1918.,
       1938., 1949., 1900., 1931., 1926., 1954., 1913., 1941., 2022.,
       1922., 1901., 1905., 1925., 1916., 1944., 1920.])

In [ ]:
data.set_index(keys="model",inplace=True)

In [ ]:
data.head()

,price,year,manufacturer,condition,cylinders,fuel,odometer,transmission,drive,size,type,paint_color
model,,,,,,,,,,,,
f-150 xlt,15000,2013.0,ford,excellent,6 cylinders,gas,128000.0,automatic,rwd,full-size,truck,black
sierra 2500 hd extended cab,27990,2012.0,gmc,good,8 cylinders,gas,68696.0,other,4wd,NaN,pickup,black
silverado 1500 double,34590,2016.0,chevrolet,good,6 cylinders,gas,29499.0,other,4wd,NaN,pickup,silver
tacoma,35000,2019.0,toyota,excellent,6 cylinders,gas,43000.0,automatic,4wd,NaN,truck,grey
colorado extended cab,29990,2016.0,chevrolet,good,6 cylinders,gas,17302.0,other,4wd,NaN,pickup,red

In [ ]:
data.drop(labels=crosstab_df.columns[1],axis=0,inplace=True)

In [ ]:
data.reset_index(inplace=True)

In [ ]:
year = np.array(data["year"])
manufacturer = np.array(data["manufacturer"])
model = np.array(data["model"])

In [ ]:
crosstab_df.columns

Index(['"t"', '%', '& altima', ''99 H1 Hummer', '(210)', '(300)',
       '(cng) 2500 express van', '(s)port (s)edan', '* vmi * ♿', '-',
       ...
       'z4 sdrive35i', 'z4 sdrive35is', 'z71', 'zdx', 'zephyr', 'zl1 camaro',
       'zr2 sonoma', 'zx2', '♿', '♿ vmi'],
      dtype='object', name='model', length=14487)

In [ ]:
data.isna().sum()

model             975
price               0
year                0
manufacturer        0
condition       13570
cylinders        1766
fuel                0
odometer          408
transmission       11
drive            2491
size            36793
type             1893
paint_color      2856
dtype: int64

In [ ]:
model = np.array(data["model"])
year = np.array(data["year"])

In [ ]:
data.shape

(144016, 13)

In [ ]:
data.isna().sum()

model             975
price               0
year                0
manufacturer        0
condition       13570
cylinders        1766
fuel                0
odometer          408
transmission       11
drive            2491
size            36793
type             1893
paint_color      2856
dtype: int64

In [ ]:
data["odometer"].fillna(value = data["odometer"].mean(),inplace = True)

In [ ]:
data.isna().sum()

model             975
price               0
year                0
manufacturer        0
condition       13570
cylinders        1766
fuel                0
odometer            0
transmission       11
drive            2491
size            36793
type             1893
paint_color      2856
dtype: int64

In [ ]:
data["condition"].value_counts()

excellent    59097
good         51580
like new     14128
fair          4546
new            732
salvage        363
Name: condition, dtype: int64

In [ ]:
data["condition"].fillna(value=data["condition"].value_counts().index[data["condition"].value_counts().argmax()],inplace=True)

In [ ]:
data.isna().sum()

model             975
price               0
year                0
manufacturer        0
condition           0
cylinders        1766
fuel                0
odometer            0
transmission       11
drive            2491
size            36793
type             1893
paint_color      2856
dtype: int64

In [ ]:
data["paint_color"].fillna(value=data["paint_color"].value_counts().index[data["paint_color"].value_counts().argmax()],inplace= True)

In [ ]:
data["paint_color"].fillna(value=data["paint_color"].value_counts().index[data["paint_color"].value_counts().argmax()],inplace= True)

In [ ]:
data["transmission"].fillna(value=data["transmission"].value_counts().index[data["transmission"].value_counts().argmax()],inplace= True)

In [ ]:
data.isna().sum()

model             975
price               0
year                0
manufacturer        0
condition           0
cylinders        1766
fuel                0
odometer            0
transmission        0
drive            2491
size            36793
type             1893
paint_color         0
dtype: int64

In [ ]:
crosstab_df = pd.crosstab(year,model,rownames=["year"],colnames=["model"])

In [ ]:
crosstab_df

model,"""t""",& altima,'99 H1 Hummer,(210),(300),(cng) 2500 express van,(s)port (s)edan,* vmi * ♿,-,- 1500,...,z4 sdrive35i,z4 sdrive35is,z71,zdx,zephyr,zl1 camaro,zr2 sonoma,zx2,♿,♿ vmi
year,,,,,,,,,,,,,,,,,,,,,
1900.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1901.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1905.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1913.0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1918.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,0,0
2019.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2021.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2022.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
crosstab_df1 = pd.crosstab([manufacturer,year],model,rownames=["manufacturer","year"],colnames=["model"])

In [ ]:
crosstab_df1

model                "t"  & altima  '99 H1 Hummer  (210)  (300)  \
manufacturer year
acura        1900.0    0         0              0      0      0
             1991.0    0         0              0      0      0
             1992.0    0         0              0      0      0
             1993.0    0         0              0      0      0
             1994.0    0         0              0      0      0
...                  ...       ...            ...    ...    ...
volvo        1966.0    0         0              0      0      0
             1967.0    0         0              0      0      0
             1970.0    0         0              0      0      0
             1971.0    0         0              0      0      0
             1972.0    0         0              0      0      0

model                (cng) 2500 express van  (s)port (s)edan  * vmi * ♿  -  \
manufacturer year
acura        1900.0                       0                0          0  0
             1991.0                       0                0          0  0
             1992.0                       0                0          0  0
             1993.0                       0                0          0  0
             1994.0                       0                0          0  0
...                                     ...              ...        ... ..
volvo        1966.0                       0                0          0  0
             1967.0                       0                0          0  0
             1970.0                       0                0          0  0
             1971.0                       0                0          0  0
             1972.0                       0                0          0  0

model                - 1500  ...  z4 sdrive35i  z4 sdrive35is  z71  zdx  \
manufacturer year            ...
acura        1900.0       0  ...             0              0    0    0
             1991.0       0  ...             0              0    0    0
             1992.0       0  ...             0              0    0    0
             1993.0       0  ...             0              0    0    0
             1994.0       0  ...             0              0    0    0
...                     ...  ...           ...            ...  ...  ...
volvo        1966.0       0  ...             0              0    0    0
             1967.0       0  ...             0              0    0    0
             1970.0       0  ...             0              0    0    0
             1971.0       0  ...             0              0    0    0
             1972.0       0  ...             0              0    0    0

model                zephyr  zl1 camaro  zr2 sonoma  zx2  ♿  ♿ vmi
manufacturer year
acura        1900.0       0           0           0    0  0      0
             1991.0       0           0           0    0  0      0
             1992.0       0           0           0    0  0      0
             1993.0       0           0           0    0  0      0
             1994.0       0           0           0    0  0      0
...                     ...         ...         ...  ... ..    ...
volvo        1966.0       0           0           0    0  0      0
             1967.0       0           0           0    0  0      0
             1970.0       0           0           0    0  0      0
             1971.0       0           0           0    0  0      0
             1972.0       0           0           0    0  0      0

[1708 rows x 14486 columns]

In [ ]:
crosstab_df.shape

(104, 14486)

In [ ]:
crosstab_df.columns[1]

'& altima'

In [ ]:
mapping_dict = dict()

for single_col in crosstab_df.columns:

  mapping_dict[crosstab_df.index[crosstab_df[single_col].argmax()]] = single_col

In [ ]:
mapping_dict

{1913.0: 'touring car',
 2006.0: '♿ vmi',
 1999.0: 'z3 coupe',
 1955.0: 'windsor deluxe',
 2012.0: 'z4 sdrive28i',
 1996.0: 'xlt f150',
 2004.0: 'z4 covertible',
 2016.0: 'z4 sdrive 35i',
 1974.0: 'x1/9',
 1997.0: 'z3 roadster',
 2019.0: 'xts luxury sedan 4d',
 2001.0: 'z3 2.5i',
 2011.0: 'z4 sdrive35i',
 2014.0: 'xv crosstrek premium 4wd',
 2010.0: 'zdx',
 2013.0: 'yukun lx',
 1983.0: 'wagoneer',
 2003.0: 'z4 roadster',
 2015.0: 'yukon xl slt',
 1971.0: 'vega panel',
 2021.0: 'x3 sdrive30i sports activity',
 2002.0: 'zx2',
 1954.0: 'sun valley',
 2005.0: 'z4 3.0i convertible',
 2007.0: 'z4 m coupe',
 2008.0: 'z4 roadster 3.0i',
 1991.0: 'z28 convertible',
 2009.0: 'z4 sdrive35is',
 1946.0: 'willys',
 1990.0: 'wrangler yj',
 1984.0: 'westfalia vanagon',
 1951.0: 'styleline deluxe',
 1960.0: 'rambler american',
 1959.0: 'xk150 se dhc',
 1964.0: 'thunderbird tudor',
 1963.0: 'unibody pickup',
 1979.0: 'w300 powerwagon',
 2017.0: 'z',
 2020.0: 'yukon slt sport utility 4d',
 1995.0: 'wrangler 4x4',
 1982.0: 'step van p3500',
 1952.0: 'wayfarer',
 1956.0: 'wagon',
 2018.0: 'zl1 camaro',
 1998.0: 'z3 m roadster',
 1970.0: 'xl convertible',
 1968.0: 'wildcat',
 1969.0: 'xke',
 1993.0: 'wrangler s sport utility',
 1923.0: 't-bucket roadster',
 1928.0: 'model a tudor',
 1930.0: 'street rod',
 1931.0: 'model a roadster',
 1937.0: 'willys coupe',
 1935.0: 'tudor',
 1936.0: 'two door sedan',
 1939.0: 'standard',
 1940.0: 'pickup truck',
 1941.0: 'super delux coupe',
 1942.0: 'pannel van',
 1947.0: 'streamliner',
 1948.0: 'willys jeepster',
 1949.0: 'styleline',
 1950.0: 'willys pickup',
 1988.0: 'yj',
 1953.0: "willy's cj3-a",
 1957.0: 'willy’s',
 1958.0: 'viking fuel truck',
 1962.0: 'tempest lemans',
 1965.0: 'tunderbird',
 1966.0: 'willys cj-5',
 1967.0: 'tempest convertible',
 1972.0: 'skylark sun coupe.',
 1973.0: 'ventura',
 1975.0: 'w100',
 1976.0: 'wrangler cj5',
 1977.0: 'unknown',
 1978.0: 'z28 camaro',
 1980.0: 'triumph spitfire 1500',
 1981.0: 'td wagon',
 1985.0: 'z28',
 1986.0: 'xj6',
 1987.0: 'wrangler laredo',
 1994.0: 'z-28',
 1989.0: 'z71',
 1992.0: 'xj40',
 2000.0: 'z3m',
 1932.0: 'vicky',
 1933.0: 'eagle',
 1934.0: 'sedan',
 1927.0: 't-bucket street rod',
 1929.0: 'roadster pickup',
 1920.0: 'Paige Glenbrook Touring',
 1938.0: 'ss100',
 1961.0: 'swb apache',
 1905.0: 'astro cargo',
 2022.0: 'p900 e450',
 1926.0: 't',
 1924.0: 'runabout roadster',
 1901.0: 'olds type r',
 1944.0: 'ww2'}

In [ ]:
mapping_dict = dict()

In [ ]:
for k in mapping_dict.keys():
  boolean_mask = (data["year"] == k[0]) & (data["manufacturer"] == k[1])
  data.loc[boolean_mask,"model"] = data.loc[boolean_mask,"model"].fillna(value=mapping_dict[k],inplace=False)

In [ ]:
for single_col in crosstab_df.columns:

  mapping_dict[crosstab_df.index[crosstab_df[single_col].argmax()]] = single_col

In [ ]:
data.isna().sum()

model             975
price               0
year                0
manufacturer        0
condition           0
cylinders        1766
fuel                0
odometer            0
transmission        0
drive            2491
size            36793
type             1893
paint_color         0
dtype: int64

In [ ]:
data["type"].value_counts()

sedan          38293
SUV            34913
truck          18989
pickup         15461
coupe           9866
hatchback       5245
convertible     4027
van             4022
wagon           3896
other           3612
mini-van        3009
offroad          550
bus              240
Name: type, dtype: int64

In [ ]:
data["type"].fillna(value=data["type"].value_counts().index[data["type"].value_counts().argmax()],inplace=True)

In [ ]:
data["cylinders"].value_counts()

6 cylinders     52001
4 cylinders     45552
8 cylinders     41779
5 cylinders      1081
10 cylinders      965
other             435
3 cylinders       338
12 cylinders       99
Name: cylinders, dtype: int64

In [ ]:
data["cylinders"].fillna(value=data["cylinders"].value_counts().index[data["cylinders"].value_counts().argmax()],inplace=True)

In [ ]:
data["model"].fillna(value=data["model"].value_counts().index[data["model"].value_counts().argmax()],inplace=True)

In [ ]:
data["drive"].value_counts()

4wd    59238
fwd    47798
rwd    34489
Name: drive, dtype: int64

In [ ]:
data.isna().sum()

model               0
price               0
year                0
manufacturer        0
condition           0
cylinders           0
fuel                0
odometer            0
transmission        0
drive            2491
size            36793
type                0
paint_color         0
dtype: int64

In [ ]:
data["drive"].fillna(data['drive'].mode()[0],inplace = True)

In [ ]:
data["size"].fillna(data["size"].mode().iloc[0], inplace = True)

In [ ]:
data.isna().sum()